import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

/**
 * The SDF glyph ranges MapLibre reads to draw street names (R-69, §14.3).
 *
 * Named for the font rather than for the glyphs: `tests/glyphs.test.ts` is
 * §9.7's state marks, which are characters on the roster and nothing to do with
 * this.
 *
 * These are **generated bytes committed to the repository** — `tools/glyphs.mjs`
 * writes them from the VT323 `.woff` — and nothing in the app can tell whether
 * they are right: a malformed range fails inside MapLibre's worker, at the
 * venue, as a map with no labels or no map at all. There is no browser in CI, so
 * what can be checked is the format, and the format is where the two mistakes
 * that matter live.
 *
 * The decoder is written out here rather than imported. `pbf` is a transitive
 * dependency of MapLibre and not ours, and a test that reads the committed
 * bytes with our own reader is checking the bytes; one that used the producer's
 * reader would be checking that a function round-trips itself.
 */

const border = 3;

interface Glyph {
  id: number;
  bitmap?: Uint8Array;
  width: number;
  height: number;
  left: number;
  top: number;
  advance: number;
}

/** Just enough protobuf: varints, zigzag, and length-delimited fields. */
function decodeRange(bytes: Uint8Array): { name: string; range: string; glyphs: Glyph[] } {
  let at = 0;
  const varint = (): number => {
    let result = 0;
    let shift = 0;
    for (;;) {
      const byte = bytes[at++]!;
      result |= (byte & 0x7f) << shift;
      if ((byte & 0x80) === 0) return result >>> 0;
      shift += 7;
    }
  };
  const zigzag = (value: number): number => (value >>> 1) ^ -(value & 1);

  const out = { name: '', range: '', glyphs: [] as Glyph[] };
  const readGlyph = (end: number): Glyph => {
    const glyph: Glyph = { id: 0, width: 0, height: 0, left: 0, top: 0, advance: 0 };
    while (at < end) {
      const key = varint();
      const field = key >> 3;
      if (field === 2) {
        const length = varint();
        glyph.bitmap = bytes.subarray(at, at + length);
        at += length;
      } else if (field === 1) glyph.id = varint();
      else if (field === 3) glyph.width = varint();
      else if (field === 4) glyph.height = varint();
      else if (field === 5) glyph.left = zigzag(varint());
      else if (field === 6) glyph.top = zigzag(varint());
      else if (field === 7) glyph.advance = varint();
      else throw new Error(`unexpected glyph field ${field}`);
    }
    return glyph;
  };
  const readStack = (end: number): void => {
    while (at < end) {
      const key = varint();
      const field = key >> 3;
      const length = varint();
      const stop = at + length;
      if (field === 1) out.name = new TextDecoder().decode(bytes.subarray(at, stop));
      else if (field === 2) out.range = new TextDecoder().decode(bytes.subarray(at, stop));
      else if (field === 3) out.glyphs.push(readGlyph(stop));
      at = stop;
    }
  };
  while (at < bytes.length) {
    const key = varint();
    expect(key >> 3).toBe(1);
    const length = varint();
    readStack(at + length);
  }
  return out;
}

const load = (range: string) =>
  decodeRange(
    new Uint8Array(
      readFileSync(new URL(`../apps/web/public/fonts/VT323/${range}.pbf`, import.meta.url)),
    ),
  );

describe('VT323 glyph ranges — R-69', () => {
  const latin = load('0-255');

  it('names the fontstack the style asks for', () => {
    // `text-font: ["VT323"]` and `glyphs: /fonts/{fontstack}/{range}.pbf` both
    // resolve through this string; a mismatch is a silent 404 per range.
    expect(latin.name).toBe('VT323');
    expect(latin.range).toBe('0-255');
    expect(latin.glyphs.length).toBeGreaterThan(150);
  });

  /**
   * MapLibre builds `(width + 6) × (height + 6)` from the metrics and hands the
   * bitmap straight to `createImage`, which throws `mismatched image size` on a
   * disagreement — and that kills the whole range, so one bad glyph is every
   * label on the map.
   */
  it('gives every glyph a bitmap of the size its metrics imply', () => {
    for (const glyph of latin.glyphs) {
      const expected = (glyph.width + 2 * border) * (glyph.height + 2 * border);
      if (glyph.bitmap === undefined) {
        // Absent is the *only* correct encoding for a glyph with no ink: present
        // and empty is a length mismatch, and `createImage` allocates the zeros
        // itself when the field is missing. A space is the one that matters.
        expect([glyph.width, glyph.height], `U+${glyph.id.toString(16)}`).toEqual([0, 0]);
      } else {
        expect(glyph.bitmap.length, `U+${glyph.id.toString(16)}`).toBe(expected);
      }
    }
  });

  it('carries the space, with an advance and no ink', () => {
    const space = latin.glyphs.find((glyph) => glyph.id === 32);
    expect(space).toBeDefined();
    expect(space!.bitmap).toBeUndefined();
    expect(space!.advance).toBeGreaterThan(0);
  });

  /**
   * The encoding itself, on a letter whose shape is known. MapLibre's shader
   * takes `(256 - 64) / 256` as the edge, so 191 is the outline: a pixel in the
   * middle of a stem has to be above it and a corner of the buffer below it. An
   * inverted field — inside dark, outside bright — passes every structural check
   * above and renders the negative of the alphabet.
   */
  it('puts the ink above the edge value and the buffer below it', () => {
    // A full stop, because it is the one glyph whose middle is certainly ink.
    // The middle of an A is the counter, which is correctly *outside*.
    const dot = latin.glyphs.find((glyph) => glyph.id === 0x2e)!;
    const stride = dot.width + 2 * border;
    const rows = dot.height + 2 * border;
    const bitmap = dot.bitmap!;
    expect(bitmap[Math.floor(rows / 2) * stride + Math.floor(stride / 2)]!).toBeGreaterThan(191);

    // And the buffer is outside on every glyph: the metrics box is tight around
    // the ink, so the outermost ring is at least two pixels clear of it.
    for (const glyph of latin.glyphs) {
      if (!glyph.bitmap) continue;
      const width = glyph.width + 2 * border;
      const height = glyph.height + 2 * border;
      for (let i = 0; i < width; i += 1) {
        expect(glyph.bitmap[i]!, `U+${glyph.id.toString(16)} top edge`).toBeLessThan(191);
        expect(
          glyph.bitmap[(height - 1) * width + i]!,
          `U+${glyph.id.toString(16)} bottom edge`,
        ).toBeLessThan(191);
      }
    }
  });

  it('carries the accented characters a Spanish street name needs', () => {
    const ids = new Set(latin.glyphs.map((glyph) => glyph.id));
    for (const character of 'ÁÉÍÓÚÑÜáéíóúñü') {
      expect(ids.has(character.codePointAt(0)!), character).toBe(true);
    }
  });

  it('ships the second range too, so a name outside Latin-1 is not a gap', () => {
    const extended = load('256-511');
    expect(extended.name).toBe('VT323');
    expect(extended.range).toBe('256-511');
    expect(extended.glyphs.length).toBeGreaterThan(0);
  });
});
