import { inflateSync } from 'node:zlib';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

/**
 * The PWA icons, which are **committed binaries generated by a script** — so
 * the two ways they go wrong are a regeneration nobody looked at, and a
 * regeneration nobody wired up.
 *
 * Neither is visible anywhere else. A maskable icon that overflows its safe
 * zone looks perfect in the repository and arrives on a launcher with its beam
 * shaved off; an icon file that exists and is not in the manifest is simply
 * never used. This suite is the only thing between either and a game night.
 */

const PUBLIC = join(import.meta.dirname, '..', 'apps', 'web', 'public');

interface Raster {
  width: number;
  height: number;
  /** Row-major, one entry per pixel: how far it is from the centre, or -1 if unlit. */
  lit: number[];
}

/**
 * Just enough PNG to answer one question.
 *
 * The generator writes colour type 2, no interlacing and filter 0 on every
 * scanline, so this reads those and asserts it rather than implementing the
 * other four filters for bytes that will never have them.
 */
function decode(name: string): Raster {
  const data = readFileSync(join(PUBLIC, name));
  expect(data.subarray(0, 8).toString('hex'), `${name} is not a PNG`).toBe('89504e470d0a1a0a');

  let offset = 8;
  let width = 0;
  let height = 0;
  const chunks: Buffer[] = [];
  while (offset < data.length) {
    const length = data.readUInt32BE(offset);
    const type = data.subarray(offset + 4, offset + 8).toString('ascii');
    const body = data.subarray(offset + 8, offset + 8 + length);
    if (type === 'IHDR') {
      width = body.readUInt32BE(0);
      height = body.readUInt32BE(4);
      expect(body[8], `${name} is not 8-bit`).toBe(8);
      expect(body[9], `${name} is not truecolour RGB`).toBe(2);
      expect(body[12], `${name} is interlaced`).toBe(0);
    }
    if (type === 'IDAT') chunks.push(Buffer.from(body));
    offset += 12 + length;
  }

  const raw = inflateSync(Buffer.concat(chunks));
  const stride = width * 3 + 1;
  const lit: number[] = [];
  for (let y = 0; y < height; y += 1) {
    expect(raw[y * stride], `${name} uses a scanline filter this reader does not do`).toBe(0);
    for (let x = 0; x < width; x += 1) {
      const red = raw[y * stride + 1 + x * 3] ?? 0;
      // The ground is `#140f0a` and the ink `#ffb000`, so red alone separates
      // them by a wide margin. The threshold catches the antialiased fringe as
      // lit, which is the point: Android crops pixels, not geometry.
      if (red <= 0x40) {
        lit.push(-1);
        continue;
      }
      const dx = (x + 0.5 - width / 2) / (width / 2);
      const dy = (y + 0.5 - height / 2) / (height / 2);
      lit.push(Math.hypot(dx, dy));
    }
  }
  return { width, height, lit };
}

/**
 * A loop and not `Math.max(...raster.lit)`.
 *
 * Spreading an array into a call passes one argument per element, and 512 x 512
 * is 262 144 of them — past the engine's limit, where it throws rather than
 * answering. It works at 192 (36 864) and fails at 512, which is a bug that
 * arrives looking exactly like a broken icon.
 */
function furthest(raster: Raster): number {
  let max = -1;
  for (const r of raster.lit) if (r > max) max = r;
  return max;
}

describe('the maskable icons', () => {
  /**
   * Android crops a maskable icon to a shape it does not tell you in advance,
   * and the only guarantee is a circle of 0,8 of the half-width. Anything
   * outside it may or may not survive, per launcher.
   *
   * **The fringe counts.** Scaled to 0,8 exactly this measured 0,8010 — one
   * pixel over, contributed by the supersampling rather than by the geometry,
   * which is exactly the kind of thing that is invisible in the source and
   * present in the file.
   */
  it.each(['icon-192-maskable.png', 'icon-512-maskable.png'])(
    '%s keeps every lit pixel inside the safe circle',
    (name) => {
      expect(furthest(decode(name))).toBeLessThanOrEqual(0.8);
    },
  );
});

describe('the any-purpose icons', () => {
  /**
   * The reason there are two files at all. A maskable icon spends 20% of its
   * canvas on padding, and used as `any` — a browser tab, a task switcher, an
   * install prompt — that reads as a small mark in a large box. If the two
   * purposes ever come out the same size, the split has quietly stopped
   * happening and one of them is wrong.
   */
  it.each([
    ['icon-192.png', 'icon-192-maskable.png'],
    ['icon-512.png', 'icon-512-maskable.png'],
  ])('%s fills more of its canvas than %s', (any, maskable) => {
    expect(furthest(decode(any))).toBeGreaterThan(furthest(decode(maskable)) + 0.1);
  });

  it('still fits inside its canvas', () => {
    // Past 1 the mark is being cut off by the edge of the image, which is a
    // different failure from being cropped by a launcher and looks the same.
    expect(furthest(decode('icon-512.png'))).toBeLessThan(1);
  });
});

describe('the manifest', () => {
  const manifest = JSON.parse(readFileSync(join(PUBLIC, 'manifest.webmanifest'), 'utf8')) as {
    background_color: string;
    theme_color: string;
    icons: { src: string; sizes: string; purpose: string }[];
  };

  /**
   * The failure this catches is the one that actually happened to this file:
   * the icons were generated and the manifest was left pointing at whatever it
   * pointed at before. A file that exists and is not listed is never used, and
   * nothing anywhere reports it.
   */
  it('lists every generated icon, at its own purpose', () => {
    const listed = manifest.icons.map((icon) => `${icon.src} ${icon.purpose}`).sort();
    expect(listed).toEqual([
      '/icon-192-maskable.png maskable',
      '/icon-192.png any',
      '/icon-512-maskable.png maskable',
      '/icon-512.png any',
    ]);
  });

  /**
   * `#0b0b0b` was a neutral near-black chosen before §9 had a palette, and it
   * made the install splash a colder black than the machine it opens into.
   * `--screen` is warm black, never `#000`.
   */
  it('opens on the screen colour', () => {
    expect(manifest.background_color).toBe('#140f0a');
    expect(manifest.theme_color).toBe('#140f0a');
  });
});
