import { constantTimeEquals } from './secret.ts';

/**
 * Signed sessions (§6.4). Players redeem an invite token for a cookie; the
 * master logs in with a password. No passwords for players, ever: the link is
 * their whole authentication, and it is what gets installed to the home screen.
 *
 * Runtime-agnostic (§6.5). HMAC is the only part that needs a platform, so it
 * arrives as an injected `Signer` — which also lets the tests drive both a real
 * WebCrypto key and a deliberately wrong one.
 *
 * Everything here is ASCII by construction: ids and session ids are generated by
 * us from a URL-safe alphabet, so the encoder can stay dependency-free instead of
 * reaching for TextEncoder.
 */

export interface Signer {
  /** base64url MAC over the message. */
  sign(message: string): Promise<string>;
}

export type SessionPayload =
  | { kind: 'PLAYER'; playerId: string; epoch: number; issuedAt: number }
  | { kind: 'MASTER'; sessionId: string; epoch: number; issuedAt: number };

/**
 * The two epochs a cookie can be checked against (R-33b).
 *
 * One number revoking every session at once is why finishing a game needs no
 * register of who is logged in — and it revoked the master along with the
 * players, so the debrief began by logging in again and re-confirming R-24, on
 * the one screen R-26 says the track is kept for.
 *
 * So there are two. `player` is bumped when a game finishes; `master` is not,
 * and only the reset moves it. A cookie is checked against the one that matches
 * its own `kind`, which is the whole of the mechanism.
 */
export interface SessionEpochs {
  player: number;
  master: number;
}

const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';

/** Ids that survive a URL, a cookie and this encoder untouched. */
export function isUrlSafeId(value: string): boolean {
  return value.length > 0 && /^[A-Za-z0-9_-]+$/.test(value);
}

export function base64UrlEncodeAscii(input: string): string {
  let out = '';
  for (let i = 0; i < input.length; i += 3) {
    const a = input.charCodeAt(i);
    const b = i + 1 < input.length ? input.charCodeAt(i + 1) : NaN;
    const c = i + 2 < input.length ? input.charCodeAt(i + 2) : NaN;
    if (a > 127 || (b > 127 && !Number.isNaN(b)) || (c > 127 && !Number.isNaN(c))) {
      throw new Error('session payloads must be ASCII');
    }
    out += ALPHABET[a >> 2];
    out += ALPHABET[((a & 3) << 4) | (Number.isNaN(b) ? 0 : b >> 4)];
    if (Number.isNaN(b)) break;
    out += ALPHABET[((b & 15) << 2) | (Number.isNaN(c) ? 0 : c >> 6)];
    if (Number.isNaN(c)) break;
    out += ALPHABET[c & 63];
  }
  return out;
}

export function base64UrlDecodeAscii(input: string): string {
  let out = '';
  let buffer = 0;
  let bits = 0;
  for (const character of input) {
    const value = ALPHABET.indexOf(character);
    if (value < 0) throw new Error('not base64url');
    buffer = (buffer << 6) | value;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      out += String.fromCharCode((buffer >> bits) & 0xff);
    }
  }
  return out;
}

export async function signSession(payload: SessionPayload, signer: Signer): Promise<string> {
  const body = base64UrlEncodeAscii(JSON.stringify(payload));
  return `${body}.${await signer.sign(body)}`;
}

/**
 * Returns null for anything that is not a currently valid session: bad shape,
 * bad signature, or an epoch from a finished game. Failing closed is the only
 * safe direction — this decides who `project()` thinks it is talking to.
 *
 * The player epoch is bumped when a game finishes, which invalidates every
 * player cookie in one move. Rotating a player's invite token alone would not:
 * the cookie carries the player id, not the token (R-08 in spirit — nothing
 * outlives the session). The master epoch is checked the same way and moved by
 * different things (R-33b, `SessionEpochs`).
 */
export async function verifySession(
  cookieValue: string,
  signer: Signer,
  expected: SessionEpochs,
): Promise<SessionPayload | null> {
  const separator = cookieValue.lastIndexOf('.');
  if (separator <= 0) return null;

  const body = cookieValue.slice(0, separator);
  const mac = cookieValue.slice(separator + 1);
  if (!constantTimeEquals(mac, await signer.sign(body))) return null;

  let parsed: unknown;
  try {
    parsed = JSON.parse(base64UrlDecodeAscii(body));
  } catch {
    return null;
  }

  const payload = parsed as Partial<SessionPayload> & Record<string, unknown>;
  if (typeof payload.issuedAt !== 'number') return null;

  // The epoch is checked against the one belonging to this cookie's kind, so the
  // kind is established first. An unrecognised kind falls through both branches
  // and returns null, which is the failing-closed this function is built on: a
  // cookie that does not say what it is is not a session.
  if (payload.kind === 'PLAYER' && typeof payload.playerId === 'string') {
    if (payload.epoch !== expected.player) return null;
    return {
      kind: 'PLAYER',
      playerId: payload.playerId,
      epoch: payload.epoch,
      issuedAt: payload.issuedAt,
    };
  }
  if (payload.kind === 'MASTER' && typeof payload.sessionId === 'string') {
    if (payload.epoch !== expected.master) return null;
    return {
      kind: 'MASTER',
      sessionId: payload.sessionId,
      epoch: payload.epoch,
      issuedAt: payload.issuedAt,
    };
  }
  return null;
}

/**
 * Which player owns an invite token, compared in time independent of how many
 * characters matched. Every player is checked even after a hit, so the answer
 * takes the same time whether the token belongs to the first player or the last.
 */
export function playerForToken<T extends { id: string; sessionToken: string }>(
  players: readonly T[],
  token: string,
): T | undefined {
  if (token.length === 0) return undefined;
  let found: T | undefined;
  for (const player of players) {
    if (constantTimeEquals(token, player.sessionToken)) found ??= player;
  }
  return found;
}
